default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cwgl_development
  username: cwgl
  password: cwgl
  host: localhost
  port: 5432

test:
  <<: *default
  database: cwgl_test

production:
  <<: *default
  database: cwgl_production
  username: cwgl
  password: <%= ENV['CWGL_DATABASE_PASSWORD'] %>
